# # host_vars/PC2-WEB.yml
# ansible_host: 172.16.6.62
# ansible_user: root

# # 서비스 관련 변수
# http_port: 80
# app_version: "1.0.0"

# # Nginx 튜닝 변수 (nginx.conf.j2에서 사용 가능)
# nginx_worker_processes: 2
# nginx_max_connections: 1024