ansible_host: 172.16.6.64
mysql_role: "master" # PC4가 Master임을 명시
mysql_server_id: 101

# 스토리지 정보
# nas_ip: "172.16.6.100"
# nas_path: "/exports/db_data"

# # SAN/NAS 마운트 경로
# nas_mount_point: "/mnt/nas_shared"
# san_device_uuid: "uuid-xxxx-xxxx"