api_base_dir: "/opt/api"
api_internal_port: 8000
docker_network_name: "api_network"

# 서비스 리스트 자동화 관리
deploy_apis:
  - { name: "weather-api", host_port: 8001, image: "fastapi-weather:latest" }
  - { name: "logistics-api", host_port: 8002, image: "fastapi-logistics:latest" }
  - { name: "energy-api", host_port: 8003, image: "fastapi-energy:latest" }