# (왼쪽: API/외부 관문)

# LB_EDGE 서버에 설치하면 좋은 패키지 or Tools
edge_packages:
  - nmap
  - traceroute
  - nc
  - iproute2

http_port: 80
waf_enabled: true

# HAProxy 백엔드 타겟 (WEB/API 그룹 참조)
lb_backend_web: "172.16.6.62"
lb_backend_api: "172.16.6.63"

# 외부 접속용 IP (AWS 연동 시 활용)
# external_ip: "1.2.3.4"